apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontnextjs
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/OWNER/REPO.git
    targetRevision: HEAD
    path: manifists/frontnextjs
  destination:
    server: https://kubernetes.default.svc
    namespace: frontnextjs
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true