Vagrant.configure("2") do |config|
  
    # First VM - argocd-vm
    config.vm.define "argocd-vm" do |ubuntu|
      ubuntu.vm.box = "bento/ubuntu-22.04"
      ubuntu.vm.hostname = "argocd-vm"
      
      ubuntu.vm.provider "vmware_desktop" do |v|
        v.memory = 2048 # Allocate 2GB of RAM or 4GB if you have enough resources (4096 MB)
        v.cpus = 2 # Allocate 2 CPU cores or 4 if you have enough resources
        v.gui = true
        v.vmx["virtualHW.version"] = "19"
      end
      
      # Provision script to install Ansible
      ubuntu.vm.provision "shell", inline: <<-SHELL
        apt update
        apt install net-tools -y
        sudo apt install -y ca-certificates curl apt-transport-https
        sleep 15
        # Install Kubectl 
        curl -sSL https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
        echo "deb https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee -a /etc/apt/sources.list.d/kubernetes.list
        apt update
        apt install -y kubectl
        sleep 15
        # Install k3s
        curl -sfL https://get.k3s.io | sh -
          # Wait for k3s to be fully up and running
        while ! kubectl get nodes -o wide; do sleep 1; done        
        sleep 15
        # Setup Kubeconfig
        mkdir -p /home/vagrant/.kube
        cp /etc/rancher/k3s/k3s.yaml /home/vagrant/.kube/config
        sudo chown $USER:$USER ~/.kube/config    
        sleep 15
        # Install ArgoCD
        sudo kubectl create namespace argocd
        sudo kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
        sudo kubectl get pods -n argocd -o wide
        sudo kubectl get svc -n argocd -o wide
        sudo kubectl port-forward svc/argocd-server -n argocd 8080:443
        sudo kubectl -n argocd get secret argocd-initial-admin-secret -o jsonpath="{.data.password}" | base64 -d > /home/vagrant/argocd_initial_password.txt

      SHELL
    end

  end