apiVersion: apps/v1
kind: Deployment
metadata:
  name: market-service-deployment
  namespace: market-service
  labels:
    app: market-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: market-service
  template:
    metadata:
      labels:
        app: market-service
    spec:
      containers:
        - name: market-service
          image: fouadallaoui/market-service:9bc00d324f0d00ac329833433c48481f637c9898
          imagePullPolicy: Always
          ports:
            - containerPort: 3003
          env:
            - name: NODE_ENV
              value: "production"
            - name: PORT
              value: "3003"
            - name: OPENTRIPMAP_API_KEY
              valueFrom:
                secretKeyRef:
                  name: market-service-secrets
                  key: opentripmap-api-key
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
          readinessProbe:
            httpGet:
              path: /
              port: 3003
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 3003
            initialDelaySeconds: 30
            periodSeconds: 30
