apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontnextjs-deployment
  namespace: frontnextjs
  labels:
    app: frontnextjs
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontnextjs
  template:
    metadata:
      labels:
        app: frontnextjs
    spec:
      containers:
        - name: frontnextjs
          image: fouadallaoui/frontnextjs:fdfdf99387ebcd4885a71621fb4b80d3cdb7c6ab
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: "production"
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 30

